# Generated by Django 4.0.6 on 2022-10-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, default='', max_length=100)),
                ('generic_link', models.CharField(blank=True, default='', max_length=500)),
                ('github_link', models.CharField(blank=True, default='', max_length=200)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=200)),
                ('facebook_link', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
