# Generated by Django 4.0.6 on 2022-11-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='posts',
            new_name='post_count',
        ),
    ]
